jenkins:
  systemMessage: From the plugin!
  clouds:
  - computeEngine:
      cloudName: "ourslave"
      configurations:
      - description: "Jenkins slaves"
        labels: "docker.build ruby.build"
        launchTimeoutSeconds: 300
        namePrefix: "jenkins-slave"
        numExecutors: 2
        region: "https://www.googleapis.com/compute/v1/projects/bsw-tech/regions/us-west1"
        retentionTimeMinutes: 120
        runAsUser: "jenkins"
        template: "https://www.googleapis.com/compute/v1/projects/bsw-tech/global/instanceTemplates/jenkins-slave"
        zone: "https://www.googleapis.com/compute/v1/projects/bsw-tech/zones/us-west1-a"
      credentialsId: "bsw-tech"
      instanceCapStr: "2"
      projectId: "bsw-tech"
unclassified:
  location:
    url: ${JENKINS_URL}
credentials:
  system:
    domainCredentials:
    - credentials:
      - googleRobotPrivateKey:
          projectId: "bsw-tech"
          serviceAccountConfig:
            json:
              filename: stuff.json
              secretJsonKey: ${gce_service_account}
      - basicSSHUserPrivateKey:
          id: bitbucket
          description: Bitbucket SSH Key
          username: git
          privateKeySource: ${bitbucket_ssh_private_key}
      - string:
          id: gemfury_key
          description: Gemfury GEM Repo Key
          secret: ${gemfury_key}
      - usernamePassword:
          id: quay_io_docker
          description: Quay IO Docker Registry username and password
          username: ${quay_io_docker_username}
          password: ${quay_io_docker_password}
      - usernamePassword:
          id: bitbucket_https
          description: Bitbucket App specific password
          username: ${bitbucket_https_username}
          password: ${bitbucket_https_password}
      - file:
          id: gem_public_key
          fileName: gem-public_cert.pem
          description: Public Key for Signing GEMs
          secretBytes: ${gem_public_key}
      - file:
          id: gem_private_key
          fileName: gem-private_key.pem
          description: Private Key for Signing GEMs
          secretBytes: ${gem_private_key}
      - usernamePassword:
          id: jira
          description: JIRA user/pass
          username: ${jira_username}
          password: ${jira_password}
