jenkins:
  systemMessage: From the plugin!
credentials:
  system:
    domainCredentials:
    - credentials:
      - googleRobotPrivateKey:
          projectId: "bsw-tech"
          serviceAccountConfig:
            json:
              filename: stuff.json
              secretJsonKey: ${somesecret}
