jenkins:
  systemMessage: From the plugin!
credentials:
  system:
    domainCredentials:
    - credentials:
      - string:
          description: "fromafiledesc"
          id: "fromafile"
          secret: ${somesecret}
