source 'https://repo.fury.io/wied03/'
source 'http://localhost:9292' if ENV['GEM_SEED_ENABLED'] == '1'

jenkins_gem = lambda do |name, version|
  gem "jenkins-plugin-proxy-#{name}", version
end

jenkins_version = ENV['JENKINS_VERSION']
fail 'Need Jenkins version!' unless jenkins_version && !jenkins_version.empty?
jenkins_gem['jenkins-core', jenkins_version]

# Standard Jenkins
jenkins_gem['build-timeout', '1.19']

# CloudBees Docker commands in Pipeline (for dealing with withRegistry, etc.)
jenkins_gem['docker-workflow', '1.17']

# Core credentials plugin
jenkins_gem['credentials', '2.1.18']

# Allow use of creds in environment variables/pipeline steps
# 1.18 does not have release notes
jenkins_gem['credentials-binding', '1.17']

# better email extensions
jenkins_gem['email-ext', '2.65']

jenkins_gem['git', '3.9.3']

# the actual core pipeline plugin
jenkins_gem['workflow-aggregator', '2.6']

# We use this for core-ansible for SSH credentials
jenkins_gem['ssh-agent', '1.17']

# Base jenkins package, adds them to console output
jenkins_gem['timestamper', '1.9']

# Workspace cleanup
jenkins_gem['ws-cleanup', '0.37']

# OWASP HTML sanitizer for text fields, standard Jenkins
jenkins_gem['antisamy-markup-formatter', '1.5']

# Authenticate via SAML (Google, Okta, etc.)
jenkins_gem['saml', '1.1.2']

# Best authorization setup available
jenkins_gem['role-strategy','2.7.0']

jenkins_gem['ec2', '1.42']

jenkins_gem['jira', '3.0.5']

# Needed to trigger multibranch pipelines from Bitbucket/webhooks
# 2.4.2 does not have release notes
jenkins_gem['cloudbees-bitbucket-branch-source', '2.4.0']

# Handy to be able to have distributed locks
jenkins_gem['lockable-resources', '2.4']

# Allow publishing HTML to the actual Jenkins build page
jenkins_gem['htmlpublisher', '1.18']
