/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'brady' at '10/15/16 7:32 PM' with Gradle 3.1
 *
 * @author brady, @date 10/15/16 7:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
